UNSEEN_VALUE = -1
MAX_VIEWS = 160
MAX_POINTS = 100_000
MIN_MASK_POINTS = 100
MIN_IOU_THRESHOLD = 0.05


DEFAULT_SAM_FOLDER = "sam"
ORIGIN_FOLDER = "origin"
SPLIT_FOLDER = "split"
COMPARE_FOLDER = "compare"

# MASK_RESULT_PATTERN = "rgb_{}.npy"